export const objections=[
{id:'caro',title:'Está caro',learn:'Primero distingue entre una comparación y un límite real de presupuesto. Escucha antes de explicar.',text:'Te entiendo. ¿Lo sientes alto por el presupuesto que tenías pensado o por lo que esperabas recibir? Si quieres, revisamos la presentación y el precio para ver si te hace sentido.'},
{id:'dinero',title:'No tengo dinero',learn:'Un límite económico se respeta. No sugieras endeudarse ni sacrificar gastos importantes.',text:'Gracias por decírmelo. No hace falta que compres ahora. Si te sirve, te comparto la información y tú me dices cuándo quieres retomarlo. ¿Te parece?'},
{id:'valor',title:'¿Por qué cuesta eso?',learn:'Explica solo datos comprobables: presentación, ingredientes documentados y precio público. No prometas resultados.',text:'Es una buena pregunta. Podemos revisar qué incluye la presentación, sus ingredientes y su precio público. ¿Qué te gustaría entender mejor para decidir si vale la pena para ti?'},
{id:'comparacion',title:'Encontré algo más barato',learn:'Compara cantidades y características equivalentes sin descalificar otras marcas ni inventar superioridad.',text:'Claro, comparar ayuda. ¿Qué producto y presentación viste? Podemos revisar cantidades, ingredientes y precio para que decidas con la información completa.'},
{id:'pensarlo',title:'Déjame pensarlo',learn:'Da espacio e identifica si queda alguna duda. Un seguimiento necesita permiso.',text:'Por supuesto, tómate tu tiempo. ¿Hay alguna duda que quieras aclarar antes? Si te parece, podemos retomarlo cuando te venga bien.'},
{id:'consulto',title:'Lo consulto con mi pareja / familia',learn:'Respeta las decisiones compartidas. Ofrece información sencilla para ambos.',text:'Claro, es importante que lo platiquen con calma. ¿Te comparto un resumen con la presentación y el precio para que lo revisen juntos? Si surgen preguntas, con gusto las vemos.'},
{id:'resultados',title:'¿Me garantizas resultados?',learn:'No prometas curas, resultados idénticos ni sustitución de atención profesional.',text:'No puedo garantizar un resultado individual. Sí puedo compartirte la información del producto para que la revises y decidas. Si tu duda es de salud, lo adecuado es consultarla con un profesional.'},
{id:'negocio',title:'¿Cuánto voy a ganar?',learn:'No inventes ingresos ni porcentajes. Usa el plan oficial vigente cuando esté disponible.',text:'No te puedo prometer una cantidad de ingresos. Para explicarte comisiones y requisitos con precisión, revisemos juntos el plan oficial de Bio4. ¿Qué te interesa conocer primero?'}
];
export const closings=[
{id:'permiso',title:'Pedir permiso para avanzar',learn:'Cuando la persona muestra interés y ya se resolvieron sus dudas.',text:'Con lo que revisamos, ¿te gustaría dar el siguiente paso o prefieres aclarar algo más? Cualquiera de las dos está bien.'},
{id:'eleccion',title:'Elegir el siguiente paso',learn:'Ofrece dos opciones reales sin dar por hecho una compra.',text:'¿Qué te ayudaría más: revisar juntos la presentación o quedarte con el resumen para decidir con calma?'},
{id:'confirmar',title:'Confirmar interés',learn:'Confirma qué quiere la persona antes de hablar de pedido.',text:'¿Esta opción se ajusta a lo que buscabas? Si te interesa, puedo confirmar contigo el total y las condiciones antes de hacer un pedido.'},
{id:'seguimiento',title:'Acordar un seguimiento',learn:'Una fecha acordada es mejor que insistir todos los días.',text:'¿Te parece que lo retomemos el día que tú prefieras? Dime cuándo te viene bien y te escribo; si no quieres continuar, no hay problema.'},
{id:'respeto',title:'Cerrar con respeto un «no»',learn:'Cerrar una conversación también puede significar aceptar que no habrá compra.',text:'Gracias por decirme. Respeto tu decisión y no te insistiré. Si en otro momento necesitas información, aquí estoy.'},
{id:'oportunidad',title:'Invitar a conocer el negocio',learn:'Propón una revisión del material, sin promesas de dinero ni compromiso.',text:'Si te interesa conocer cómo funciona Bio4, podemos revisar la información oficial y tus preguntas. ¿Te gustaría agendar una conversación breve, sin compromiso?'}
];
export const lessons=[
{title:'Conoce tus primeros productos',body:'Elige dos productos. Identifica nombre, presentación y precio público. Revisa ingredientes disponibles y evita prometer resultados. Practica explicarlos en una frase sencilla.',action:'Explorar productos',route:'productos',task:'Puedo explicar dos productos sin inventar beneficios.'},
{title:'Publica tu primer Estado',body:'Abre una ficha y entra en Compartir. Copia el texto para Estado, revisa que corresponda al producto y publícalo manualmente en WhatsApp. Una invitación clara es suficiente.',action:'Preparar mi Estado',route:'productos',task:'Publiqué mi primer Estado con datos del producto.'},
{title:'Inicia conversaciones',body:'Empieza con permiso y una pregunta abierta. Por ejemplo: «¿Te gustaría que te comparta la información? ¿Qué te gustaría conocer?». Escucha la respuesta antes de recomendar.',action:'Practicar una conversación',route:'practicar',task:'Inicié una conversación y escuché lo que la persona buscaba.'},
{title:'Responde al precio',body:'Di el precio público y la presentación con claridad. Si surge una objeción, pregunta si se trata del presupuesto o de entender el valor. Respeta el límite económico.',action:'Ver respuestas de precio',route:'objeciones',task:'Puedo responder al precio sin justificarme ni presionar.'},
{title:'Practica un cierre',body:'Resume lo que la persona busca y pregunta por un siguiente paso. Aceptar un «no» también es una buena conversación. Practica con distintas dificultades.',action:'Ir al simulador',route:'practicar',task:'Practiqué un cierre que permite decir sí o no.'},
{title:'Haz seguimiento con permiso',body:'Acuerda una fecha y un motivo para retomar. Registra únicamente lo necesario; evita datos de salud o información sensible. Cumple la fecha y respeta si no desea continuar.',action:'Organizar seguimientos',route:'seguimientos',task:'Acordé y registré un seguimiento con permiso.'}
];
const definitions=[
['precio','Primera compra, primera duda','Ana','Vio un Estado de Gano Congruencia y nunca lo ha probado.','Me interesa, pero $1,857 se me hace mucho para probar.','Quiero conocer la presentación antes de decidir.','Me preocupa pagar sin entender bien qué estoy comprando.'],
['dinero','El presupuesto de esta semana','Luis','Tiene gastos prioritarios esta semana.','No tengo dinero ahorita.','Esta semana necesito cubrir otros gastos.','No quiero comprometer dinero que necesito para mi casa.'],
['precio','Entender el precio','Martha','Busca una explicación sencilla, sin discurso de venta.','¿Por qué cuesta eso?','Quiero saber qué incluye y cuánto trae.','Todavía no veo qué lo hace adecuado para mí.'],
['comparacion','Dos opciones en la mesa','Diego','Encontró un producto de otra marca.','Encontré algo más barato.','El otro envase parece más grande.','Quiero comparar cantidades, no solo marcas.'],
['pensarlo','Decidir con calma','Sofía','Pidió información y ahora quiere espacio.','Déjame pensarlo.','Me interesa, pero necesito revisar la información.','No quiero decidir hoy.'],
['familia','Una decisión compartida','Carlos','Suele consultar las compras con su pareja.','Lo voy a consultar con mi esposa.','Los dos organizamos los gastos de la casa.','Me gustaría que ella también pudiera preguntar.'],
['producto','¿Qué contiene?','Elena','Pregunta por ingredientes de Bio.Gru.','¿Qué ingredientes tiene Bio.Gru?','Quiero leer la etiqueta y saber la presentación.','No me basta con que me digas que es natural.'],
['producto','Esperar algo realista','Pedro','Busca certeza antes de comprar.','¿Me garantizas que me va a funcionar?','Prefiero saber qué puedo esperar sin promesas.','No quiero pagar por una garantía que nadie puede dar.'],
['seguimiento','Retomar con permiso','Lucía','Acordó que le escribirías hoy para revisar dudas.','Sí vi tu mensaje, pero he estado ocupada.','No he tenido tiempo de leer el resumen.','Esta semana no quiero más mensajes del tema.'],
['cierre','Interés sin prisa','Jorge','Ya conoce la presentación y el precio.','Sí me interesa. ¿Qué sigue?','Quiero saber el total y las condiciones antes de confirmar.','No quiero que se haga un pedido sin que yo lo confirme.'],
['negocio','Conocer Bio4 desde cero','Paola','Tiene curiosidad por el negocio, sin experiencia.','¿Cómo funciona lo de ser socio?','Quiero conocer actividades, requisitos y costos.','No quiero que me prometan dinero fácil.'],
['negocio','Ingresos sin promesas','Andrés','Pregunta cuánto podría ganar.','¿Cuánto voy a ganar al mes?','Necesito entender de qué dependen las comisiones.','Quiero ver el plan oficial, no ejemplos inventados.'],
['dinero','Esperar a la quincena','Rosa','Quiere posponer una compra sin sentirse juzgada.','Tal vez en la quincena, hoy no puedo.','Prefiero esperar a organizar mis gastos.','No quiero apartar ni pagar nada por ahora.'],
['comparacion','Lo mismo en internet','Miguel','Vio un anuncio con un precio diferente.','En internet lo vi más barato.','No sé si era la misma presentación.','Antes de decidir quiero comparar el precio total.'],
['pensarlo','Una duda que no ha dicho','Valeria','Tiene interés pero no entiende bien la presentación.','Lo voy a pensar y te aviso.','La verdad no entendí bien qué incluye.','Todavía quiero aclarar eso antes de avanzar.'],
['familia','Compartir con la familia','Fernando','Desea enviarle información a un familiar.','Se lo voy a enseñar a mi mamá.','Le ayudaría un resumen claro con el precio.','No quiero decirle que ya está decidido.'],
['producto','Elegir por presentación','Gabriela','Compara Gano Congruencia de sobres con Hogar.','¿Qué diferencia hay entre sobres y Hogar?','Me importa la presentación y cuánto contiene cada opción.','No supongas que son iguales en todo.'],
['producto','La etiqueta primero','Raúl','Quiere información precisa de un producto.','¿Tienes la lista completa de ingredientes?','Quiero revisar el envase antes de comprar.','No quiero confundir ingredientes destacados con fórmula completa.'],
['seguimiento','Un mensaje sin respuesta','Diana','No contestó el primer resumen que le enviaste.','Perdón, se me pasó responder.','Por ahora solo estoy viendo opciones.','No quiero sentir que te debo una respuesta.'],
['cierre','Aclarar antes del pedido','Hugo','Le interesa comprar pero faltan condiciones.','¿Me lo puedes conseguir?','Primero quiero confirmar precio, envío y entrega.','No des por hecho la disponibilidad ni la fecha.'],
['negocio','Vender por internet','Claudia','Pregunta por el e-commerce de Bio4.','¿Bio4 me da una tienda en línea?','Quiero ver qué incluye el servicio y sus requisitos.','Prefiero que lo revisemos en el material oficial.'],
['negocio','Comisiones y niveles','Ricardo','Vio nombres de niveles y no entiende el plan.','¿Qué comisión me toca y cómo subo de nivel?','Quiero conocer requisitos y porcentajes vigentes.','No quiero cifras aproximadas; necesito el documento oficial.'],
['precio','Cuánto trae por ese precio','Verónica','Está comparando presentaciones de Kenko Café.','¿Cuánto trae por ese precio?','Quiero que me indiques la presentación exacta.','Si hay varias, comparemos una a una.'],
['dinero','Sin pagos a presión','Arturo','No puede comprar y teme que insistas.','Si no puedo pagarlo, ¿me vas a insistir?','Prefiero no comprar en este momento.','Quiero que respetes esa decisión.'],
['comparacion','La recomendación de un amigo','Natalia','Un amigo le recomendó otra marca.','Mi amigo dice que la otra marca es mejor.','Quiero comparar datos sin descalificar a nadie.','¿Podemos revisar información concreta de ambas?'],
['pensarlo','Cerrar el tema por hoy','Sergio','Le molestan los mensajes repetidos.','Déjame pensarlo; por favor no me escribas diario.','Si tengo dudas, yo te busco.','No quiero agendar seguimiento por ahora.'],
['familia','No todos están convencidos','Patricia','Su pareja tiene dudas sobre el producto.','Mi pareja no está convencida.','Le gustaría entender el precio y qué incluye.','No quiero sentir que tengo que convencerla a fuerza.'],
['seguimiento','Después de revisar la ficha','Óscar','Leyó la información y tiene una duda concreta.','Ya lo vi, pero no sé si es para mí.','Necesito aclarar lo que busco antes de elegir.','No quiero que me recomiendes algo solo para vender.'],
['cierre','Un no también se respeta','Adriana','Después de revisar, decidió no comprar.','Gracias, pero decidí que no.','Prefiero dejarlo aquí.','No quiero buscar otra opción en este momento.'],
['negocio','Empezar con expectativas claras','Daniel','Quiere saber qué tendría que hacer al empezar.','Si empiezo, ¿qué tendría que hacer primero?','Quiero conocer requisitos y aprender a conversar.','Necesito entender tiempo, costos y actividades sin promesas de ingresos.']
];
export const topics={precio:'Precio y valor',dinero:'Presupuesto',comparacion:'Comparación',pensarlo:'Déjame pensarlo',familia:'Pareja y familia',producto:'Producto',seguimiento:'Seguimiento',cierre:'Cierre',negocio:'Oportunidad'};
export const scenarios=definitions.map((d,i)=>({id:`s${String(i+1).padStart(2,'0')}`,topic:d[0],title:d[1],person:d[2],context:d[3],opening:d[4],need:d[5],concern:d[6]}));
export const difficulties=['Nuevo','Intermedio','Difícil'];
export const dimensions=['Descubrir necesidad','Hacer preguntas','Claridad y valor','Evitar presión','Avance / cierre'];
