const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function signals(text){const t=normalize(text);return {need:/busca|necesit|importa|presupuesto|preocupa|espera|interesa|entiendo|prioridad|prefiere/.test(t),question:/[?¿]|cuentame|dime|comparte/.test(t),value:/presentacion|ingrediente|precio|incluye|contenido|cantidad|etiqueta|compar|informacion|resumen|oficial|requisito/.test(t),respect:/sin compromiso|sin presion|calma|tu tiempo|no hay problema|respeto|no (?:te )?insist|no hace falta|cuando|si (?:te |quieres|prefieres)|puedes|decid|esta bien|no puedo garantizar|no puedo prometer/.test(t),next:/revis|compart|retoma|agend|confirm|cuando|te parece|te gustaria|siguiente|escrib|no (?:te )?insist|respeto tu decision|dejamos|aqui estoy/.test(t),pressure:/(?:compra|paga|decide) (?:ya|ahora)|tienes que comprar|no puedes perder|ultima oportunidad|endeuda|pide prestado|te lo (?:garantizo|aseguro)|cura(?:r)? (?:la|el|tu)|ganancia garantizada|dinero facil|ingresos garantizados/.test(t)};}
export function evaluate(responses,scenario=null){
 const meaningful=responses.filter(s=>s.trim().length>=12),sig=meaningful.map(signals);
 const coverage=k=>{const n=sig.filter(s=>s[k]).length;return n===0?0:n===1?80:100;};
 const pressure=sig.some(s=>s.pressure);
 const boundary=['s29','s26'].includes(scenario?.id)&&sig.some(s=>s.respect)&&!pressure;
 const scores=[coverage('need'),coverage('question'),coverage('value'),pressure?0:meaningful.length?Math.max(40,coverage('respect')):0,coverage('next')];
 const feedback=[scores[0]>=50?'Buscaste entender qué necesita la persona.':'Pregunta qué busca, qué le preocupa o cuál es su presupuesto.',scores[1]>=50?'Abriste espacio para que el prospecto responda.':'Incluye una pregunta abierta y espera su respuesta.',scores[2]>=50?'Usaste señales de información concreta. Revisa que cada dato sea correcto.':'Explica presentación, precio o información documentada con sencillez.',pressure?'Detectamos una frase de presión o promesa. Reformúlala y permite decidir con libertad.':scores[3]>=50?'Incluiste expresiones de respeto y libertad de decisión.':'Haz explícito que puede esperar o decir que no.',scores[4]>=50?'Propusiste avanzar o cerrar la conversación.':'Acuerda un siguiente paso con permiso, o respeta el cierre del tema.'];
 if(boundary){scores[0]=100;scores[1]=100;scores[2]=100;scores[4]=100;feedback[0]='Reconociste su necesidad de cerrar el tema.';feedback[1]='Ante un «no» explícito, no hace falta seguir preguntando.';feedback[2]='Una despedida clara es suficiente; no necesitas añadir argumentos de venta.';feedback[4]='Respetar el límite de la persona es un cierre válido.';}
 return {scores,total:Math.round(scores.reduce((a,b)=>a+b,0)/5),feedback,pressure};
}
export function shouldFinish(s,difficulty,responses){const f=signals(responses.at(-1)||'');return responses.length>=roundCount(difficulty)||(['s29','s26'].includes(s.id)&&f.respect&&!f.pressure);}
export function prospectReply(s,difficulty,responses){
 const last=responses.at(-1)||'',f=signals(last),n=responses.length,t=normalize(last);
 if(f.pressure)return 'Eso me hace sentir presión. No quiero decidir así. ¿Podemos hablar sin prometer resultados ni apresurarme?';
 if(s.topic==='dinero'&&/credito|tarjeta|prestamo|abono/.test(t))return 'Prefiero no endeudarme. Mi límite de presupuesto sigue siendo el mismo.';
 if(s.id==='s29'||s.id==='s26')return f.respect?'Gracias por respetar mi decisión. Dejemos aquí la conversación.':n===1?s.need:n===2?s.concern:'Gracias. Prefiero que dejemos aquí la conversación.';
 if(s.topic==='negocio'&&/\d+\s*%|\$\s*\d/.test(t))return '¿De qué documento oficial sale esa cifra? Prefiero revisarlo antes de darla por cierta.';
 if(n===1)return f.question?`${s.need} ¿Qué información me puedes compartir?`:`${s.concern} ¿Podrías preguntarme primero qué necesito?`;
 if(n===2){if(difficulty==='Nuevo')return f.value?'Gracias, eso me ayuda. ¿Cuál sería un siguiente paso sin compromiso?':`Todavía me gustaría entender algo concreto. ${s.need}`;return `${s.concern} ${difficulty==='Difícil'?'Además, no quiero comprometerme todavía. ¿Cómo lo manejarías?':'¿Qué me propones?'} `;}
 if(n===3&&difficulty==='Intermedio')return f.respect?'Me ayuda que respetes mi tiempo. ¿Podemos acordar cómo retomar, sin compromiso?':'Antes de seguir, quiero saber si está bien esperar o decir que no. ¿Qué me propones?';
 if(n===3&&difficulty==='Difícil'){const challenges={precio:'También encontré otra opción más barata. ¿Cómo haríamos una comparación justa?',dinero:'Además, mi familia y yo tenemos otras prioridades. No quiero asumir una deuda.',comparacion:'Mi pareja prefiere la otra opción. ¿Puedes ayudarme a comparar sin descalificarla?',pensarlo:'Mi presupuesto también es limitado. Prefiero no decidir hoy.',familia:'Además del precio, nos preocupa no tener toda la información. ¿Qué podemos revisar?',producto:'Quiero comparar con otra marca y no espero resultados garantizados. ¿Qué datos revisaríamos?',seguimiento:'También quiero dejar claro que no deseo mensajes frecuentes. ¿Cómo lo acordamos?',cierre:'Antes de confirmar, quiero consultarlo con mi pareja. No hagas el pedido todavía.',negocio:'Mi familia duda y yo no quiero promesas de ingresos. ¿Cómo podríamos informarnos?'};return challenges[s.topic];}
 if(n===4&&difficulty==='Difícil')return f.respect?'Aprecio que me des espacio. ¿Cómo cerrarías esto respetando lo que te dije?':'Necesito que quede claro que puedo decir que no. ¿Qué me dirías?';
 return f.respect?'Gracias por la información y por darme espacio para decidir.':'Gracias. Voy a revisar la información a mi ritmo.';
}
export function roundCount(difficulty){return difficulty==='Nuevo'?3:difficulty==='Intermedio'?4:5;}
export function sampleExam(items,random=Math.random){const pool=[...items];for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,10).map(s=>s.id);}
